# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9045daa95162a43dcf9caf258f02574b1f65dab37d14293d834d4edf3b8a9a2062c0cc5be44cc7395369196bd1daa7d801426d6b626cfa6aefaa908ca26ceafb

test:
  secret_key_base: ca876f91200d24513944cb17300d2a46882a9ab3352da1c918c9c462de0a91e64d72d0130b305ceb3f3363984e13ba0da5c6fb634885dcf7ec74bc77970ea80e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
